### ISSUE TITLE
Cant install on mautic 1.2.4

### ISSUE THREAD

**Issue by FarhadF** [kuzmany/MauticAnalyticsTaggingBundle#2]
Hi

Followed instructions:
1.Cloned files into plugins directory.
2.Changed owner to www-data (using apache2 on debian jessie)
3.install/update showed 0 added.

thanks in advance

**Comment by kuzmany** [comment]
Hi,

Try clear cache.

**Comment by FarhadF** [comment]
Thanks for fast reply, Clearing the cache did the charm.
Farhad
