### ISSUE TITLE
Add email category to utm_campaign and new utm_content option

### ISSUE THREAD

**Issue by luizeof** [kuzmany/MauticAnalyticsTaggingBundle#5]
Hi @kuzmany ... MauticAnalyticsTaggingBundle makes easier add Google Analytics UTM tags to our e-mails. Thanks a Lot!

I just made some adjustments that we use with our mautic installations and i want to share with you on pull request #4 :

- Translating to Brazilian Portuguese (pt_BR). ee65f32d1544a122d72ea6719c0c8451290149f8
- Add E-mail Category as an option to utm_campaign. 755b737a3fde784251e6a49a186a85c6897d12b5
- Add utm_content with email category, email name or email subject. 6665cedd16e51621a0fcdbb6fd6f3aaa91fb3285
- Fix a bug that not show the tooltip on plugin form. c5b7e71906f76c34d388597ae2ba3efa4e5f4503
- Update README to follow the changes. 334820dfae41c036d9451c272018db113d90ed13
- Update the default options to utm_campaign and utm_content. 31bdfebf91f4db78b2725da44861f78396533d64
 
I hope you accept.

**Comment by kuzmany** [comment]
Thanks. Great commits, I will add it soon

**Comment by luizeof** [comment]
Thanks @kuzmany
